# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d75e09e0d7e756d025b2fba56e3b0fac9fffeafaaf4f57607b11a38eb02c86c86710ff1a584fbf3a5d470c48a27c64f85f7bdd97ff55dce68757f046dbe38ebb

test:
  secret_key_base: 8f46cfcdbb92a00e930baa43632d1f44c3fc34c35c6bf6c485388043ce2a5381d1e7f99b48bfd83f25a8273eeae99667006cf83ee08b10fc574d21cde143c4cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
